---
title: "COVID-19 in derivatives"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    favicon: world-health-organization-computer-icons-business-organization_fav.png
    source_code: "https://github.com/pernaletec/covid19_derivatives"
    social: [ "twitter", "facebook", "instagram", "pinterest" ]
    includes: 
      in_header: "google-analytics.html"
runtime: shiny
---

```{r setup, include=FALSE}

library(flexdashboard)
library(rmarkdown)
library(highcharter)
library(rjson)
library(jsonlite)
library(dplyr)
library(RColorBrewer)
library(xts)
library(tsbox)
```

Global view
===================================== 

Inputs {.sidebar data-width=300}
-------------------------------------

### About

**COVID19 in derivatives** allows to monitor de rate of change of the spread of Coronavirus as well as the change of the rate of change. 

In technical words you can track the __first__ and the __second derivative__ of the growing phenomena.  

### Derivative selection 

- Actual value (zero derivative)
- Rate of change (first derivative)
- Change of rate of change (second derivative)

```{r}


selectInput("derivative", "Derivative:",
                c("Zero" = "zero",
                  "First" = "first",
                  "Second" = "second"))

```

### Source of data

Available in [Github](https://github.com/CSSEGISandData/COVID-19) by [JHU CSSE](https://systems.jhu.edu/research/public-health/ncov/). 


Row {.tabset}
-------------------------------------

### Last Zero, First or Second derivative per country
    
```{r, echo = FALSE}

output$map_chart = renderHighchart({
  
  library('httr')
  
  confirmed = read.csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv', stringsAsFactors = FALSE)
  
  #(head(confirmed))
  
  agg_i = aggregate(confirmed$X3.16.20, by=list(confirmed$Country.Region), sum)
  agg_ii = aggregate(confirmed$X3.15.20, by=list(confirmed$Country.Region), sum)
  agg_iii = aggregate(confirmed$X3.14.20, by=list(confirmed$Country.Region), sum)
  
  #print(agg_i)
  
  didt = agg_i$x - agg_ii$x
  
  di2dt = agg_ii$x - agg_iii$x
  
  ddidt = didt - di2dt
  

  #print(didt)
  
  countries = agg_i$Group.1
  
  derivative = input$derivative

  if (derivative == 'zero') {
    downloads = agg_i$x
    label_title = 'Current cases (# persons)'
    }
  
  if (derivative == 'first') {
    downloads = didt
    label_title = 'Last rate of growth (#persons/day)'
    }
  
  if (derivative == 'second') {
    downloads = ddidt
    label_title = 'Diff. in last rates of growths ((#persons/day)/day)'
  }
  
  ### end new code
  
  world <- jsonlite::fromJSON(txt = "world-palestine-highres.geo.JSON", simplifyVector = FALSE)
  mapdata = get_data_from_map(world)
  missing = countries %in% mapdata$name
  missing_indx = which(missing == FALSE)
  countries[missing_indx]
  
  #print(countries[missing_indx])
  
  # There are differences between the country names between sourceforge.net and world-palestine-highres.geo.JSON
  
#      [1] "Aruba"                          "Cayman Islands"                
#  [3] "Congo (Brazzaville)"            "Congo (Kinshasa)"              
#  [5] "Cote d'Ivoire"                  "Cruise Ship"                   
#  [7] "Curacao"                        "Czechia"                       
#  [9] "Eswatini"                       "Guadeloupe"                    
# [11] "Guernsey"                       "Holy See"                      
# [13] "Jersey"                         "Korea, South"                  
# [15] "Martinique"                     "North Macedonia"               
# [17] "occupied Palestinian territory" "Reunion"                       
# [19] "Serbia"                         "Taiwan*"                       
# [21] "US"  
#     
  original_names = c("US", "United States","Viet Nam","Serbia","Tanzania", "Congo - Kinshasa","Lao People's Democratic Republic","Bahamas","Korea","Brunei Darussalam")
                      
  replacement = c("United States of America", "United States of America", "Vietnam", "Republic of Serbia", "United Republic of Tanzania", "Democratic Republic of the Congo", "Laos", "The Bahamas", "South Korea", "Brunei")
  
  for (i in 1:length(replacement))  {
    if (isTRUE(original_names[i] %in% countries)) {
      countries = replace(x = countries,countries == original_names[i],as.character(replacement[i]))
      }
  }
  
  # Merging system with its respective countries. In some cases there are some simplifications. Venezuela += Aruba p.e.
  
  if (isTRUE("Hong Kong" %in% countries)) downloads[countries=="China"] = downloads[countries=="China"] + downloads[countries=="Hong Kong"]
  
  if (isTRUE("New Caledonia" %in% countries))  downloads[countries=="France"] = downloads[countries=="France"] + downloads[countries=="New Caledonia"] 
  
  if (isTRUE("Guadeloupe" %in% countries)) downloads[countries=="France"] = downloads[countries=="France"] + downloads[countries=="Guadeloupe"]
  
  if (isTRUE("Reunion" %in% countries)) downloads[countries=="France"] = downloads[countries=="France"] + downloads[countries=="Reunion"]
  
  if (isTRUE("Palestinian Territory" %in% countries)) downloads[countries=="Israel"] = downloads[countries=="Israel"] + downloads[countries=="Palestinian Territory"]
    
  if (isTRUE("Bermuda" %in% countries))  downloads[countries=="United Kingdom"] = downloads[countries=="United Kingdom"] + downloads[countries=="Bermuda"]
  
  if (isTRUE("Aruba" %in% countries)) downloads[countries=="Venezuela"] = downloads[countries=="Venezuela"]  + downloads[countries=="Aruba"] 
    
  if (isTRUE("Netherlands Antilles" %in% countries)) downloads[countries=="Venezuela"] = downloads[countries=="Venezuela"]  + downloads[countries=="Netherlands Antilles"]
  
  if (isTRUE("Bonaire, Saint Eustatius and Saba" %in% countries)) downloads[countries=="Venezuela"] = downloads[countries=="Venezuela"]  + downloads[countries=="Bonaire, Saint Eustatius and Saba"]
  
  fullLocUnknown = c("Unknown","Europe (specific country unknown)", "Anonymous Proxy", "Satellite Provider","Asia/Pacific Region (specific country unknown)",  "Virgin Islands", "Cook Islands", "Timor-Leste") 
  #Last three must be evaluated carefully
  
  fullLocAdded = c("Hong Kong", "Netherlands Antilles", "New Caledonia", "Palestinian Territory", "Aruba", "Bermuda", "Reunion", "Guadeloupe", "Bonaire, Saint Eustatius and Saba")
  
  locUnknown=c()
  locAdded=c()
  
  for (i in length(fullLocUnknown)) if (isTRUE(fullLocUnknown[i] %in% countries)) locUnknown = c(locUnknown,fullLocUnknown[i])
  
  for (i in length(fullLocAdded)) if (isTRUE(fullLocAdded[i] %in% countries)) locAdded = c(locAdded,fullLocAdded[i])
  
  locToRemove = c(locUnknown, locAdded)
  
  toRemove = countries %in% locToRemove 
  
  countries = countries[!toRemove]
  downloads = downloads[!toRemove]
  
  table(countries %in% mapdata$name)
  
  data_world_downloads = data.frame(countries, downloads)
  
  n <- 4
  colstops <- data.frame(q = 0:n/n,
                         c = RColorBrewer::brewer.pal(n = 5, name = "YlOrRd")) %>%
    highcharter::list_parse2()

  highchart(type = "map") %>%
  hc_add_series_map(map = world,
                showInLegend = FALSE,
                nullColor = "#ffffff",
                borderWidth = 0,
                borderColor = "#FAFAFA",
                df = data_world_downloads,
                value = "downloads",
                joinBy = c("name", "countries"),
                name = label_title,
                dataLabels = list(enabled = TRUE, format = '{point.name}')) %>%
    hc_colorAxis(stops = colstops) %>%
    hc_chart(backgroundColor = "#ffffff") %>%
    hc_mapNavigation(enabled = TRUE) 
    
})

highchartOutput("map_chart")

```

### Zero, First or Second derivative in trends

```{r}

output$line_chart = renderHighchart({
    
  library('httr')
  
  confirmed = read.csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv', stringsAsFactors = FALSE)
  

  genTotal_i = apply(X = confirmed[,5:length(confirmed[1,])],2, FUN = sum)
  
  genTotal_ii = rep(0,length(genTotal_i)-1)
  
  for (i in length(genTotal_i):2) {
    genTotal_ii[i-1] = genTotal_i[i] - genTotal_i[i-1]
  } 
  
  
  genTotal_iii = rep(0,length(genTotal_ii)-1)
  
  for (i in length(genTotal_ii):2) {
    genTotal_iii[i-1] = genTotal_ii[i] - genTotal_ii[i-1]
    } 

  derivative = input$derivative

  if (derivative == 'zero') {
    dwnlm = genTotal_i
    label_title = 'Current cases (# persons)'
    dates = seq(from = as.Date('2020/01/22'), to = as.Date('2020/03/16'), by = "day")
    }
  
  if (derivative == 'first') {
    dwnlm = genTotal_ii
    label_title = 'Last rate of growth (#persons/day)'
    dates = seq(from = as.Date('2020/01/23'), to = as.Date('2020/03/16'), by = "day")
    }
  
  if (derivative == 'second') {
    dwnlm = genTotal_iii
    label_title = 'Diff. in last rates of growths ((#persons/day)/day)'
    dates = seq(from = as.Date('2020/01/24'), to = as.Date('2020/03/16'), by = "day")
  }
  
  data_xts <- xts(dwnlm, order.by=as.Date(dates, "%d/%m/%Y"))
  
  highchart(type = "stock") %>% 
    hc_yAxis_multiples(
      list(title = list(text = label_title))
    ) %>% 
    hc_add_series(data = data_xts,
                name = label_title,
                color = last(RColorBrewer::brewer.pal(n = 5, name = "Reds")), yAxis = 0)
  
})
    
highchartOutput("line_chart")

```

Country view
===================================== 

Inputs {.sidebar data-width=300}
-------------------------------------

### About

**COVID19 in derivatives** allows to monitor de rate of change in the growing of Coronavirus as well as the change of the rate of change. 

In technical words you can track the __first__ and the __second derivative__ of the growing phenomena.  

### Derivative selection 

- Actual value (zero derivative)
- Rate of change (first derivative)
- Change of rate of change (second derivative)

```{r}


selectInput("derivative_country", "Derivative:",
                c("Zero" = "zero",
                  "First" = "first",
                  "Second" = "second"))

```

### Country selection

```{r}

# Node selection
uiOutput(outputId = "country_sel")

```

### Source of data

Available in [Github](https://github.com/CSSEGISandData/COVID-19) by [JHU CSSE](https://systems.jhu.edu/research/public-health/ncov/). 


Row {.tabset}
-------------------------------------

### Zero, First or Second derivative in trends

```{r}

output$line_chart_country = renderHighchart({
 
  library('httr')
  
  confirmed = read.csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv', stringsAsFactors = FALSE)
  
  
  if (!is.null(input$country_sel)){
    
    country = input$country_sel
    
    print(head(confirmed))
    
    genTotal_i = apply(X = confirmed[confirmed$Country.Region == country,5:length(confirmed[1,])],2, FUN = sum)
  
    #print('genTotal_i')
    #print(genTotal_i)
    
    genTotal_ii = rep(0,length(genTotal_i)-1)
    
    for (i in length(genTotal_i):2) {
      genTotal_ii[i-1] = genTotal_i[i] - genTotal_i[i-1]
    } 
    
    
    genTotal_iii = rep(0,length(genTotal_ii)-1)
    
    for (i in length(genTotal_ii):2) {
      genTotal_iii[i-1] = genTotal_ii[i] - genTotal_ii[i-1]
      } 
  
    derivative = input$derivative_country
  
    if (derivative == 'zero') {
      dwnlm = genTotal_i
      label_title = 'Current cases (# persons)'
      dates = seq(from = as.Date('2020/01/22'), to = as.Date('2020/03/16'), by = "day")
      }
    
    if (derivative == 'first') {
      dwnlm = genTotal_ii
      label_title = 'Last rate of growth (#persons/day)'
      dates = seq(from = as.Date('2020/01/23'), to = as.Date('2020/03/16'), by = "day")
      }
    
    if (derivative == 'second') {
      dwnlm = genTotal_iii
      label_title = 'Diff. in last rates of growths ((#persons/day)/day)'
      dates = seq(from = as.Date('2020/01/24'), to = as.Date('2020/03/16'), by = "day")
    }
    
    ### end new code    
  
    data_xts <- xts(dwnlm, order.by=as.Date(dates, "%d/%m/%Y"))
    
    highchart(type = "stock") %>% 
      hc_yAxis_multiples(
        list(title = list(text = label_title))
      ) %>% 
      hc_add_series(data = data_xts,
                  name = label_title,
                  color = last(RColorBrewer::brewer.pal(n = 5, name = "Reds")), yAxis = 0)
    }
})
    
highchartOutput("line_chart_country")


output$country_sel <- renderUI({

  library('httr')
  
  confirmed = read.csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv', stringsAsFactors = FALSE)
  
 all_countries = sort(unique(confirmed[,2]))
 
 print('all_countries')
 print(all_countries)
 
 print('input$country_sel')
 print(input$country_sel)
    
  if (!is.null(input$country_sel)) selectInput(inputId = "country_sel", label = "Country", choices = all_countries, selected = input$country_sel)
  else selectInput(inputId = "country_sel", label = "Country", choices = all_countries, selected = "Venezuela")
 
 #selectInput(inputId = "country_sel", label = "Country", choices = all_countries, selected)
 
 
})

```

